name: Auto-Format Code

on:
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        
    - name: Format code with Black
      run: black -t py312 .
      
    - name: Import sorting with isort
      run: isort .
        
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "🤖 Auto-Format Code with Black and isort"
        commit_user_name: "GitHub Actions"
        commit_user_email: "actions@github.com"
